// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/file_hash.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class FileHashBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FileHashBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FileHashBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<ffi.Char> sha256_file_native(ffi.Pointer<ffi.Char> filepath) {
    return _sha256_file_native(filepath);
  }

  late final _sha256_file_nativePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('sha256_file_native');
  late final _sha256_file_native = _sha256_file_nativePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  void free_sha256_string(ffi.Pointer<ffi.Char> ptr) {
    return _free_sha256_string(ptr);
  }

  late final _free_sha256_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'free_sha256_string',
      );
  late final _free_sha256_string = _free_sha256_stringPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();
}
